entities:
  - name: customer
    join_key: customer_id
    description: Customer identifier

data_sources:
  customer_transactions:
    type: file
    path: data/customer_data.parquet
    timestamp_field: event_timestamp

feature_views:
  customer_stats:
    source_name: customer_transactions
    entities: [customer]
    ttl_days: 7
    schema:
      - name: amount
        dtype: FLOAT
      - name: transaction_count
        dtype: INT64